const express = require("express");
const app = express();
const port = 3000 || process.env.port;
const path = require("path");
const routes = require("./routes");
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
routes.appRoutes(app);
app.use(express.static(path.join(__dirname, "../public")));
app.listen(port);
